services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: money
    networks:
      - money_net
  backend:
    image: money/backend
    build:
      dockerfile: back-end/Dockerfile
      network: host
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/money
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: P@ssw0rd
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
    ports:
      - "8085:8080"
    networks:
      - money_net
    depends_on:
      - postgres

networks:
  money_net: