version: "3.9"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: money
    networks:
      - money_net
  backend:
    image: money/backend
    build:
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres/money
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
      BOT_CREATOR_ID: ${BOT_CREATOR_ID}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8085:8080"
    networks:
      - money_net
    depends_on:
      - postgres

networks:
  money_net:
