### POST
POST http://localhost:8080/transaction
Content-Type: application/json

{
  "timestamp": "2023-01-10T13:02:01Z",
  "type": "INCOME",
  "account": {
    "id": 1
  },
  "currency": "EUR",
  "sum": 1000,
  "user": {
    "id": 1
  },
  "comment": "test"
}

### POST
POST http://localhost:8080/transaction
Content-Type: application/json

{
"timestamp": "2023-05-01T13:02:01Z",
"type": "EXPENSE",
"account": {
"id": 1
},
"currency": "EUR",
"sum": 9.99,
"user": {
"id": 1
},
"comment": "test"
}

### GET ALL
GET http://localhost:8080/transaction

### GET FIRST
GET http://localhost:8080/transaction/1

### PUT
PUT http://localhost:8080/transaction/1
Content-Type: application/json

{
  "id": 1,
  "timestamp": "2023-02-10T13:02:01Z",
  "type": "INCOME",
  "account": {
    "id": 1
  },
  "currency": "EUR",
  "sum": 9.99,
  "user": {
    "id": 1
  },
  "comment": "test test"
}

### DELETE
DELETE http://localhost:8080/transaction/1

