INSERT INTO category (group_name, name, created_timestamp, updated_timestamp)
VALUES ('Income', 'Salary', now(), now()),
       ('Income', 'Interest', now(), now()),
       ('Housing', 'Mortgage', now(), now()),
       ('Housing', 'Rent', now(), now()),
       ('Housing', 'Home maintenance and repairs', now(), now()),
       ('Housing', 'Property taxes', now(), now()),
       ('Housing', 'HOA dues', now(), now()),
       ('Housing', 'Home warranty', now(), now()),
       ('Housing', 'Large appliances', now(), now()),
       ('Utilities', 'Electricity', now(), now()),
       ('Utilities', 'Gas', now(), now()),
       ('Utilities', 'Heating', now(), now()),
       ('Utilities', 'Water', now(), now()),
       ('Utilities', 'Internet', now(), now()),
       ('Utilities', 'Cable', now(), now()),
       ('Utilities', 'Phone', now(), now()),
       ('Utilities', 'Cellphone', now(), now()),
       ('Utilities', 'Trash', now(), now()),
       ('Utilities', 'Recycling', now(), now()),
       ('Utilities', 'Sewer', now(), now()),
       ('Food', 'Groceries', now(), now()),
       ('Food', 'Restaurants', now(), now()),
       ('Food', 'Takeout', now(), now()),
       ('Food', 'Fast food', now(), now()),
       ('Food', 'Coffee shops', now(), now()),
       ('Food', 'Alcohol', now(), now()),
       ('Transportation', 'Gas/Fuel', now(), now()),
       ('Transportation', 'Car maintenace and repair', now(), now()),
       ('Transportation', 'Parking fees', now(), now()),
       ('Transportation', 'Public transportation', now(), now()),
       ('Transportation', 'Airplane tickets', now(), now()),
       ('Transportation', 'Taxis', now(), now()),
       ('Debt & Loan Payments', 'Credit card debt', now(), now()),
       ('Debt & Loan Payments', 'Student loans', now(), now()),
       ('Debt & Loan Payments', 'Personal loans', now(), now()),
       ('Debt & Loan Payments', 'Auto loan', now(), now()),
       ('Debt & Loan Payments', 'Alimony', now(), now()),
       ('Insurance', 'Medical insurance', now(), now()),
       ('Insurance', 'Dental insurance', now(), now()),
       ('Insurance', 'Mortgage insurance', now(), now()),
       ('Insurance', 'Renters insurance', now(), now()),
       ('Insurance', 'Car insurance', now(), now()),
       ('Insurance', 'Life insurance', now(), now()),
       ('Insurance', 'Property insurance', now(), now()),
       ('Insurance', 'Pet insurance', now(), now()),
       ('Healthcare', 'Primary care', now(), now()),
       ('Healthcare', 'Specialty care', now(), now()),
       ('Healthcare', 'Dental care', now(), now()),
       ('Healthcare', 'Urgent care', now(), now()),
       ('Healthcare', 'Medical devices', now(), now()),
       ('Healthcare', 'Health supplements', now(), now()),
       ('Healthcare', 'Medications', now(), now()),
       ('Kids', 'Child support', now(), now()),
       ('Kids', 'Child education', now(), now()),
       ('Clothing', 'Adults’ clothing', now(), now()),
       ('Clothing', 'Adults’ shoes', now(), now()),
       ('Clothing', 'Children’s clothing', now(), now()),
       ('Clothing', 'Children’s shoes', now(), now()),
       ('Personal Care', 'Haircuts', now(), now()),
       ('Personal Care', 'Cosmetics', now(), now()),
       ('Personal Care', 'Spa', now(), now()),
       ('Personal Care', 'Salon visits', now(), now()),
       ('Personal Care', 'Gym membership', now(), now()),
       ('Household', 'Household Supplies', now(), now()),
       ('Household', 'Furniture', now(), now()),
       ('Household', 'Home decorations', now(), now()),
       ('Household', 'Small appliances', now(), now()),
       ('Household', 'Tools', now(), now()),
       ('Pets', 'Pet food', now(), now()),
       ('Pets', 'Pet supplies', now(), now()),
       ('Pets', 'Grooming', now(), now()),
       ('Pets', 'Vet visits', now(), now()),
       ('Pets', 'Pet medication', now(), now()),
       ('Entertainment', 'Magazines', now(), now()),
       ('Entertainment', 'Going out/Bars', now(), now()),
       ('Entertainment', 'Hobbies', now(), now()),
       ('Entertainment', 'Small electronics', now(), now()),
       ('Entertainment', 'Sporting events', now(), now()),
       ('Entertainment', 'Concerts', now(), now()),
       ('Entertainment', 'Movies', now(), now()),
       ('Entertainment', 'Games', now(), now()),
       ('Entertainment', 'Subscriptions', now(), now()),
       ('Education', 'Books', now(), now()),
       ('Education', 'Coaching', now(), now()),
       ('Education', 'Conferences', now(), now()),
       ('Education', 'Webinars', now(), now()),
       ('Education', 'Courses', now(), now()),
       ('Charity/Donations', 'Church donations', now(), now()),
       ('Charity/Donations', 'Donations to nonprofit organizations', now(), now()),
       ('Charity/Donations', 'Online donations', now(), now()),
       ('Charity/Donations', 'Gifts', now(), now()),
       ('Savings', 'Emergency fund', now(), now()),
       ('Savings', 'Retirement', now(), now()),
       ('Savings', 'Investments', now(), now()),
       ('Savings', 'Vacation', now(), now()),
       ('Savings', 'New car', now(), now()),
       ('Savings', 'College fund', now(), now()),
       ('Work', 'Software', now(), now()),
       ('Work', 'Home office', now(), now()),
       ('Work', 'Business lunch', now(), now()),
       ('Other', 'Balance adjustment income', now(), now()),
       ('Other', 'Balance adjustment expense', now(), now()),
       ('Other', 'Bank fees', now(), now()),
       ('Other', 'Credit card fees', now(), now());