INSERT INTO users (id, name, login, password, telegram_id)
VALUES (1, 'Nikolai', 'nikolai', '_', 0),
       (2, 'Ekaterina', 'ekaterina', '_', 1);

ALTER SEQUENCE users_seq RESTART WITH 3;

INSERT INTO account (id, name, type, currency, owner_id)
VALUES (1, 'Nikolai Euro Cahs', 0, 'EUR', 1),
       (2, 'Nikolai Euro Card', 1, 'EUR', 1),
       (3, 'Nikolai Euro Bank Account', 2, 'EUR', 1),
       (4, 'Ekaterina Euro Cahs', 0, 'EUR', 2),
       (5, 'Ekaterina Euro Card', 1, 'EUR', 2),
       (6, 'Ekaterina Euro Bank Account', 2, 'EUR', 2);

ALTER SEQUENCE account_seq RESTART WITH 7;

INSERT INTO account_payment_type(id, account_type, payment_method)
VALUES (1, 0, 'BANKNOTE'),
       (2, 1, 'CARD');

ALTER SEQUENCE account_payment_type_seq RESTART WITH 3;

INSERT INTO user_default_account (id, user_id, type, account_id)
VALUES (1, 1, 0, 1),
       (2, 1, 1, 2),
       (3, 2, 0, 4),
       (4, 2, 1, 5);

ALTER SEQUENCE user_default_account_seq RESTART WITH 5;

INSERT INTO category (id, category_group, category_name, transaction_type)
VALUES (1, 'Income', 'Salary', 0),
       (2, 'Income', 'Interest', 0),
       (3, 'Housing', 'Mortgage', 1),
       (4, 'Housing', 'Rent', 1),
       (5, 'Housing', 'Home maintenance and repairs', 1),
       (6, 'Housing', 'Property taxes', 1),
       (7, 'Housing', 'HOA dues', 1),
       (8, 'Housing', 'Home warranty', 1),
       (9, 'Housing', 'Large appliances', 1),
       (10, 'Utilities', 'Electricity', 1),
       (11, 'Utilities', 'Gas', 1),
       (12, 'Utilities', 'Heating', 1),
       (13, 'Utilities', 'Water', 1),
       (14, 'Utilities', 'Internet', 1),
       (15, 'Utilities', 'Cable', 1),
       (16, 'Utilities', 'Phone', 1),
       (17, 'Utilities', 'Cellphone', 1),
       (18, 'Utilities', 'Trash', 1),
       (19, 'Utilities', 'Recycling', 1),
       (20, 'Utilities', 'Sewer', 1),
       (21, 'Food', 'Groceries', 1),
       (22, 'Food', 'Restaurants', 1),
       (23, 'Food', 'Takeout', 1),
       (24, 'Food', 'Fast food', 1),
       (25, 'Food', 'Coffee shops', 1),
       (26, 'Food', 'Alcohol', 1),
       (27, 'Transportation', 'Gas/Fuel', 1),
       (28, 'Transportation', 'Car maintenace and repair', 1),
       (29, 'Transportation', 'Parking fees', 1),
       (30, 'Transportation', 'Public transportation', 1),
       (31, 'Transportation', 'Airplane tickets', 1),
       (32, 'Transportation', 'Taxis', 1),
       (33, 'Debt & Loan Payments', 'Credit card debt', 1),
       (34, 'Debt & Loan Payments', 'Student loans', 1),
       (35, 'Debt & Loan Payments', 'Personal loans', 1),
       (36, 'Debt & Loan Payments', 'Auto loan', 1),
       (37, 'Debt & Loan Payments', 'Alimony', 1),
       (38, 'Insurance', 'Medical insurance', 1),
       (39, 'Insurance', 'Dental insurance', 1),
       (40, 'Insurance', 'Mortgage insurance', 1),
       (41, 'Insurance', 'Renters insurance', 1),
       (42, 'Insurance', 'Car insurance', 1),
       (43, 'Insurance', 'Life insurance', 1),
       (44, 'Insurance', 'Property insurance', 1),
       (45, 'Insurance', 'Pet insurance', 1),
       (46, 'Healthcare', 'Primary care', 1),
       (47, 'Healthcare', 'Specialty care', 1),
       (48, 'Healthcare', 'Dental care', 1),
       (49, 'Healthcare', 'Urgent care', 1),
       (50, 'Healthcare', 'Medical devices', 1),
       (51, 'Healthcare', 'Health supplements', 1),
       (52, 'Healthcare', 'Medications', 1),
       (53, 'Kids', 'Child support', 1),
       (54, 'Kids', 'Child education', 1),
       (55, 'Clothing', 'Adults’ clothing', 1),
       (56, 'Clothing', 'Adults’ shoes', 1),
       (57, 'Clothing', 'Children’s clothing', 1),
       (58, 'Clothing', 'Children’s shoes', 1),
       (59, 'Personal Care', 'Haircuts', 1),
       (60, 'Personal Care', 'Cosmetics', 1),
       (61, 'Personal Care', 'Spa', 1),
       (62, 'Personal Care', 'Salon visits', 1),
       (63, 'Personal Care', 'Gym membership', 1),
       (64, 'Household', 'Household Supplies', 1),
       (65, 'Household', 'Furniture', 1),
       (66, 'Household', 'Home decorations', 1),
       (67, 'Household', 'Small appliances', 1),
       (68, 'Household', 'Tools', 1),
       (69, 'Pets', 'Pet food', 1),
       (70, 'Pets', 'Pet supplies', 1),
       (71, 'Pets', 'Grooming', 1),
       (72, 'Pets', 'Vet visits', 1),
       (73, 'Pets', 'Pet medication', 1),
       (74, 'Entertainment', 'Magazines', 1),
       (75, 'Entertainment', 'Going out/Bars', 1),
       (76, 'Entertainment', 'Hobbies', 1),
       (77, 'Entertainment', 'Small electronics', 1),
       (78, 'Entertainment', 'Sporting events', 1),
       (79, 'Entertainment', 'Concerts', 1),
       (80, 'Entertainment', 'Movies', 1),
       (81, 'Entertainment', 'Games', 1),
       (82, 'Entertainment', 'Subscriptions', 1),
       (83, 'Education', 'Books', 1),
       (84, 'Education', 'Coaching', 1),
       (85, 'Education', 'Conferences', 1),
       (86, 'Education', 'Webinars', 1),
       (87, 'Education', 'Courses', 1),
       (88, 'Charity/Donations', 'Church donations', 1),
       (89, 'Charity/Donations', 'Donations to nonprofit organizations', 1),
       (90, 'Charity/Donations', 'Online donations', 1),
       (91, 'Charity/Donations', 'Gifts', 1),
       (92, 'Savings', 'Emergency fund', 1),
       (93, 'Savings', 'Retirement', 1),
       (94, 'Savings', 'Investments', 1),
       (95, 'Savings', 'Vacation', 1),
       (96, 'Savings', 'New car', 1),
       (97, 'Savings', 'College fund', 1),
       (98, 'Work', 'Software', 1),
       (99, 'Work', 'Home office', 1),
       (100, 'Work', 'Business lunch', 1),
       (101, 'Other', 'Balance adjustment income', 0),
       (102, 'Other', 'Balance adjustment expense', 1),
       (103, 'Other', 'Bank fees', 1),
       (104, 'Other', 'Credit card fees', 1);


ALTER SEQUENCE category_seq RESTART WITH 105;
